// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.2
// source: encoding/proto/pb/wrapper.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type     string     `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Request  *anypb.Any `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Response *anypb.Any `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *EventWrapper) Reset() {
	*x = EventWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encoding_proto_pb_wrapper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventWrapper) ProtoMessage() {}

func (x *EventWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_encoding_proto_pb_wrapper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventWrapper.ProtoReflect.Descriptor instead.
func (*EventWrapper) Descriptor() ([]byte, []int) {
	return file_encoding_proto_pb_wrapper_proto_rawDescGZIP(), []int{0}
}

func (x *EventWrapper) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventWrapper) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventWrapper) GetRequest() *anypb.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *EventWrapper) GetResponse() *anypb.Any {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_encoding_proto_pb_wrapper_proto protoreflect.FileDescriptor

var file_encoding_proto_pb_wrapper_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x01, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x57,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x72, 0x69, 0x6b, 0x72,
	0x73, 0x6e, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encoding_proto_pb_wrapper_proto_rawDescOnce sync.Once
	file_encoding_proto_pb_wrapper_proto_rawDescData = file_encoding_proto_pb_wrapper_proto_rawDesc
)

func file_encoding_proto_pb_wrapper_proto_rawDescGZIP() []byte {
	file_encoding_proto_pb_wrapper_proto_rawDescOnce.Do(func() {
		file_encoding_proto_pb_wrapper_proto_rawDescData = protoimpl.X.CompressGZIP(file_encoding_proto_pb_wrapper_proto_rawDescData)
	})
	return file_encoding_proto_pb_wrapper_proto_rawDescData
}

var file_encoding_proto_pb_wrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_encoding_proto_pb_wrapper_proto_goTypes = []interface{}{
	(*EventWrapper)(nil), // 0: wrapper.EventWrapper
	(*anypb.Any)(nil),    // 1: google.protobuf.Any
}
var file_encoding_proto_pb_wrapper_proto_depIdxs = []int32{
	1, // 0: wrapper.EventWrapper.request:type_name -> google.protobuf.Any
	1, // 1: wrapper.EventWrapper.response:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_encoding_proto_pb_wrapper_proto_init() }
func file_encoding_proto_pb_wrapper_proto_init() {
	if File_encoding_proto_pb_wrapper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encoding_proto_pb_wrapper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encoding_proto_pb_wrapper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_encoding_proto_pb_wrapper_proto_goTypes,
		DependencyIndexes: file_encoding_proto_pb_wrapper_proto_depIdxs,
		MessageInfos:      file_encoding_proto_pb_wrapper_proto_msgTypes,
	}.Build()
	File_encoding_proto_pb_wrapper_proto = out.File
	file_encoding_proto_pb_wrapper_proto_rawDesc = nil
	file_encoding_proto_pb_wrapper_proto_goTypes = nil
	file_encoding_proto_pb_wrapper_proto_depIdxs = nil
}
